### ISSUE TITLE
Detect when defid process/RPC is down 

### ISSUE THREAD

**Issue by GuybrushX** [defichain-api/masternode-health-server#40]
**Describe the bug**
I wanted to update defid and test masternode-health/[DFI Signal](https://dfi-signal.com/) Telegram bot for "node down" notifications and expected that masternode-health will push something like "node down" and the [DFI Signal](https://dfi-signal.com/) Telegram bot would inform me about it. Didn't happen ;-)

**To Reproduce**
1. stop defid
2. wait for your cronjob to kick in or run masternode-health manually
3. I got the message on the 1st run: 503 Server Error: Service Unavailable for url: http://localhost:8554/
-> Obviously that's true ;-)
On subsequent tries I always get a stacktrace and the following messages (much more than 5 minutes passed already):
```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe2eec40a00>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8554): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2eec40a00>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".local/bin/masternode-health", line 8, in <module>
    sys.exit(main())
  File "/home/defichain/.local/lib/python3.8/site-packages/masternode_health/monitor.py", line 217, in main
    nodeMonitor.processNode()
  File "/home/defichain/.local/lib/python3.8/site-packages/masternode_health/monitor.py", line 156, in processNode
    self._processNodeInfo()
  File "/home/defichain/.local/lib/python3.8/site-packages/masternode_health/monitor.py", line 111, in _processNodeInfo
    self.checkNodes = self._checkAreNodesMining()
  File "/home/defichain/.local/lib/python3.8/site-packages/masternode_health/monitor.py", line 92, in _checkAreNodesMining
    mininginfo = self._rpcquery('getmininginfo')
  File "/home/defichain/.local/lib/python3.8/site-packages/masternode_health/monitor.py", line 67, in _rpcquery
    response = requests.post(self.rpchost, auth=(self.rpcuser, self.rpcpassword), headers=headers, data=json.dumps(data), timeout=1000)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8554): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2eec40a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Expected behavior**
Push and record the "node down" message to the masternode-health server so [DFI Signal](https://dfi-signal.com/) and other tools can process it.

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - masternode-health version 1.0.2

**Comment by adrian-schnell** [comment]
you're right - DFI Signal should inform you. at the moment only the manual fetching of the data is implemented. rest will follow soonish :D
